version: '3.4'
services:
  tunneling:
    image: coolersport/ssh-tunneling:1.0
    read_only: true
    ports:
    - 2222:2222
    volumes:
    - home:/home:rw
    - ./opt:/opt:ro
volumes:
  home:
    labels:
    - "app=sshtunneling"
